version: "2"   # Official Doc: https://golangci-lint.run/usage/configuration/
run:
  timeout: 30m
issues:
  new-from-rev: v0.0.2
linters:
  settings:
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 2
      min-occurrences: 2
    lll:
      line-length: 140
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - wrapperFunc
        - dupImport # https://github.com/go-critic/go-critic/issues/845
        - ifElseChain
        - octalLiteral
    funlen:
      lines: 100
      statements: 60
  exclusions:
    paths:
      - "^zz_generated.*"
    rules:
      # disable rules for test files
      - path: _test\.go
        linters:
          - dogsled # because `_, _, _, err := foo(); assert.Error(t, err)` isn't unusual
          - funlen # `func Test...` tend to be unavoidably long
          - gocritic # numerous checks which aren't critical for test files
          - lll # A number of tests have long strings that can't be split
          - goconst # these are only test files
  # Default set of linters.
  # The value can be:
  # - `standard`: https://golangci-lint.run/usage/linters/#enabled-by-default
  # - `all`: enables all linters by default.
  # - `none`: disables all linters by default.
  # - `fast`: enables only linters considered as "fast" (`golangci-lint help linters --json | jq '[ .[] | select(.fast==true) ] | map(.name)'`).
  default: none
  # Enable specific linter.
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - revive
    - govet
    - ineffassign
    - lll
    - nakedret
    - copyloopvar
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
formatters:
  enable:
    - goimports
