name: Build
on:
  push:
    branches:
      - "main"
  pull_request: {}

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup go environment
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: 'go.mod'

      - name: Use golangci-lint
        uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6.1.1
        with:
          version: v2.4.0

      - name: Run tests
        run: make test

      - name: Check licenses
        run: make check-licenses

      - name: Generated files are up-to-date
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Generated files are not up to date"
            git status --porcelain
            exit 1
          fi
