name: Build
on:
  push:
    branches:
      - "main"
  pull_request: {}

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Setup go environment
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: 'go.mod'

      - name: Use golangci-lint
        uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64 # v6.0.1
        with:
          version: v1.56.2
          args: --print-issued-lines

      - name: Run tests
        run: make test

      - name: Check licenses
        run: make check-licenses

      - name: Generated files are up-to-date
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Generated files are not up to date"
            git status --porcelain
            exit 1
          fi
