name: Build
on:
  push:
    branches:
      - "main"
  pull_request: {}

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup go environment
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: 'go.mod'

      - name: Use golangci-lint
        uses: golangci/golangci-lint-action@ec5d18412c0aeab7936cb16880d708ba2a64e1ae # v6.2.0
        with:
          version: v1.61.0
          args: --print-issued-lines

      - name: Run tests
        run: make test

      - name: Check licenses
        run: make check-licenses

      - name: Generated files are up-to-date
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Generated files are not up to date"
            git status --porcelain
            exit 1
          fi
