name: Require change fragment

on:
  pull_request:
    branches:
      - main
    types:
      # On by default if you specify no types.
      - "opened"
      - "reopened"
      - "synchronize"
      # For `skip-label` only.
      - "labeled"
      - "unlabeled"

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    steps:
      - name: "Check for changelog entry"
        # TODO use a released version when a new tag is created
        uses: brettcannon/check-for-changed-files@1d976b36a566141b41cdafbbc63a89eb54ec8a8a # main
        with:
          file-pattern: ".changes/unreleased/*.yaml"
          skip-label: "skip changelog"
          failure-message: "Missing a changelog file in ${file-pattern}; please add one or apply the ${skip-label} label to the pull request"
          token: "${{ github.token }}"
