name: Update tooling
on:
  workflow_dispatch:
  schedule:
    - cron: 0 3 * * 1-5

jobs:
  changie:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          token: "${{ secrets.RELEASE_TOKEN }}"

      - name: Get latest version
        id: latest
        run: |
          echo 'output<<_GitHubActionsFileCommandDelimiter_' >> $GITHUB_OUTPUT
          curl --silent --fail-with-body https://api.github.com/repos/miniscruff/changie/releases | jq --raw-output '[.[].tag_name | select(contains("-") | not)] | max_by( ltrimstr("v") | split(".") | map(tonumber) )' >> $GITHUB_OUTPUT
          echo '_GitHubActionsFileCommandDelimiter_' >> $GITHUB_OUTPUT

      - name: Update GitHub workflows
        env:
          VER: ${{ steps.latest.outputs.output }}
        run: ./.github/update-changie-to-latest-version.sh "$VER"

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5.0.1
        id: commit
        with:
          create_branch: true
          branch: "changie-${{ steps.latest.outputs.output }}"
          commit_message: |
            Update changie to ${{ steps.latest.outputs.output }}

            Update the changie version to [${{ steps.latest.outputs.output }}](https://github.com/miniscruff/changie/releases/tag/${{ steps.latest.outputs.output }})

      - name: Raise PR and close any old ones
        if: steps.commit.outputs.changes_detected == 'true'
        env:
          GITHUB_TOKEN: "${{ secrets.RELEASE_TOKEN }}"
          REPO: "${{ github.repository }}"
        run: |
          currentUser=$(gh api user | jq -r '.login')

          existing=$(gh pr list --repo "${REPO}" --search "'Update changie' author:$currentUser state:open" --json number)

          gh pr create --repo "${REPO}" --fill-first --label "skip changelog"

          currentPr=$(gh pr view --json number | jq '.number')

          echo "$existing" | jq -r '.[].number' | xargs -I % -n 1 gh pr close % --repo "${REPO}" --comment "Superseded by #${currentPr}" --delete-branch

          echo "PR https://github.com/${REPO}/pull/${currentPr} raised" >> $GITHUB_STEP_SUMMARY
