name: Update tooling
on:
  workflow_dispatch:
  schedule:
    - cron: 0 3 * * 1-5

jobs:
  changie:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: "${{ secrets.RELEASE_TOKEN }}"

      - name: Get latest version
        id: latest
        run: |
          echo 'output<<_GitHubActionsFileCommandDelimiter_' >> $GITHUB_OUTPUT
          curl --silent --fail-with-body https://api.github.com/repos/miniscruff/changie/releases | jq --raw-output '[.[].tag_name | select(contains("-") | not)] | max_by( ltrimstr("v") | split(".") | map(tonumber) )' >> $GITHUB_OUTPUT
          echo '_GitHubActionsFileCommandDelimiter_' >> $GITHUB_OUTPUT

      - name: Update GitHub workflows
        env:
          VER: ${{ steps.latest.outputs.output }}
        run: ./.github/update-changie-to-latest-version.sh "$VER"

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5.0.1
        id: commit
        with:
          create_branch: true
          branch: "changie-${{ steps.latest.outputs.output }}"
          commit_message: |
            Update changie to ${{ steps.latest.outputs.output }}

            Update the changie version to [${{ steps.latest.outputs.output }}](https://github.com/miniscruff/changie/releases/tag/${{ steps.latest.outputs.output }})

      - name: Raise PR and close any old ones
        if: steps.commit.outputs.changes_detected == 'true'
        env:
          GITHUB_TOKEN: "${{ secrets.RELEASE_TOKEN }}"
          GH_REPO: "${{ github.repository }}"
        run: .github/raise-pr.sh "Update changie"
